### ISSUE TITLE
no need for iframe

### ISSUE THREAD

**Issue by s0urcelab** [JohyC/Recessive-url-Forward#2]
vercel本来就是提供前端资源托管的，你自己服务器只提供接口就行了。

**Comment by JohyC** [comment]
> vercel本来就是提供前端资源托管的，你自己服务器只提供接口就行了。

🤣 我都忘记这个仓库当时为啥建了。。一直没用。。

**Comment by s0urcelab** [comment]
> 

是没用自建换商用的vps了么？

**Comment by s0urcelab** [comment]
是没用自建换商用的vps了么？

**Comment by JohyC** [comment]
> 是没用自建换商用的vps了么？

也不是。我在玩homelab，家里有公网ip。小房间里面放了几台组装的机器，天天在转。

**Comment by s0urcelab** [comment]
> > 是没用自建换商用的vps了么？
> 
> 也不是。我在玩homelab，家里有公网ip。小房间里面放了几台组装的机器，天天在转。

我现在就是，我的站前端都是vercel托管，然后接口部署在自己机器上
